### ISSUE TITLE
Collection Names

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-support#30]
690 (local subject access) is currently not in default mapping. 

923 (Hoover note) is not mapped (e.g. 923   Hoover Offsite Newspaper Project (HONP))
924 (Hoover note) is not mapped (e.g. 924    Iraqi textbook collection)

Can we use the actual collection names somewhere else? Holdings/items? 
Per Vitus:  Really should be at item level, but currently at title level so that is path we will pursue now.

Sarah has agreed that SW will work on using the Collection Name.  Vitus and Jeanette will work on pulling Collection Names out of 690 and into 795. 

@vitustang do the above Hoover notes fall into the same Collection Name category? Should they also be moved to the 795?

What is the criteria for a collection? Locally organized? Vendor organized? Both?

**Comment by shelleydoljack** [comment]
I think historically, we've wanted to use the collection name in the 690 field for discovery purposes but were never able to achieve that since 690 also contained local subject headings. Does 690 need to map to a FOLIO instance field? Is it currently in the MARC in SRS? If it is in the MARC in SRS, then I'm not sure it needs to be added to the mapping to FOLIO instance field unless it is needed for searching and faceting within FOLIO.

**Comment by jlkalchik** [comment]
Gryphon Search is currently looking into moving the collection names to another field. See notes in https://jirasul.stanford.edu/jira/browse/SW-3919

**Comment by ahafele** [comment]
See above for updated description.

**Comment by vitustang** [comment]
@ahafele about whether Hoover note 923 and 924 would also migrate to the 795 field being set up for just "collection names", I don't really know what Hoover's practice has been with regard to what they put in those two fields. My guess is that they contain heterogeneous contents. If they also contain collection names, then I would advise Hoover to move those to our new 795 field so that all collection names will be in the same field

**Comment by ahafele** [comment]
Per Hoover: Hoover uses collection name data in 590 (local, item-specific notes and collection name data) and 690 (collection name data) fields. We also use 923, some 924 fields for local notes (923/4 intended for Staff Only). Would like to see all of these notes in the Instance record. 690: specifically in newspaper bibliographic records where we then want to connect the overarching archival collection that they can be found in

**Comment by ahafele** [comment]
Per Lane: Lane - Don’t have collection names used in meaningful ways, usually represented as locations. For e-resources maintain vendors in records 852 and 844 in holdings. Depending on collection criteria this could be used

**Comment by ahafele** [comment]
Will make an instance note type = Collection name and map there.

**Comment by ahafele** [comment]
@vitustang @jlkalchik see example here - https://folio-test.stanford.edu/inventory/view/7d64192c-e571-444a-b1cb-902ca1194378.
What subfields should be included? Right now I just have $a.

**Comment by ahafele** [comment]
795 added to mapping - make close ticket to document this separately
