### ISSUE TITLE
264 $c ending in -

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#76]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>The dash is being stripped it for all 264 $c making open ended dates seem static. Also in this record there are 2x 264 $3 which are not part of the default mapping but could be helpful to serial staff? Maybe ask Kay or Camelia?
<strong>Instance HRID: </strong>`a349984`
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by jlkalchik** [comment]
From metadata subgroup slack: Kay Teel: Serials bibliographic display: Repeated 26x displays in Inventory, but the MARC $3 data doesn't display. $3 gives when each different publisher/imprint was valid. This may be unsolvable, because I don't see anywhere in Inventory where $3 might be mapped, but I wanted to mention it as a situation where Inventory display won't make any sense. Viewing & understanding the MARC record will be required to interpret the display. Example: Instance HRID a14308585

**Comment by ahafele** [comment]
$3 has been added to the mapping
